#define PROJ_SCREENMODE MODE_FAST_16COLOR
#define PROJ_PERSISTENCE false
#define PROJ_FPS 60
#define PROJ_HIGH_RAM HIGH_RAM_MUSIC
#define PROJ_PERSISTENCE true
#define PROJ_ENABLE_SOUND 1
#define PROJ_AUD_FREQ 16000
#define PROJ_SOUND_BUFFER 0
